services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=mongodb://mongodb:27017/submissiox

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for HTTP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
      - ./public:/usr/src/app/public  # Mount the public directory
    depends_on:
      - app  # Ensure the app is started before Nginx

volumes:
  mongo-data:
